import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export default function Home({ data }) {
  console.log(data);
  return (
    <>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav>
          <img />

          <Link href="/">Home</Link>
          <Link href="/events">Events</Link>
          <Link href="/about-us">about-us</Link>
        </nav>
      </header>
      <main className={styles.main}>
        {data.map((ev) => {
          return (
            <Link key={ev.id} href={`/events/${ev.id}`}>
              <Image width={300} height={300} alt={ev.title} src={ev.image} />
              <h2>{ev.title}</h2>
              <p>{ev.description}</p>
            </Link>
          );
        })}
      </main>
      <footer className="{styles.footer}">2023 Time to code-Nasrullah</footer>
    </>
  );
}

export async function getServerSideProps() {
  // const data = await import('/data/data.json');
  const { events_categories } = await import('/data/data.json');
  console.log(events_categories);

  // const {eventss_categories} = data;

  return {
    props: {
      data: events_categories,
    },
  };
}
